version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
  json-server:
    container_name: json-server
    image: json-server-image
    build: 
      context: .
      dockerfile: app/db/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./app/db:/db
    command: sh -c "json-server /db/db.json --port 3001 --host 0.0.0.0"
