// export const API_HOST = 'http://localhost:3001';
export const API_HOST = 'http://ntugether.zapto.org:4000';
export const API_EMAIL_VERIFY = `${API_HOST}/user/emailSend`;
export const API_SIGN_UP = `${API_HOST}/user/signup`;
export const API_LOGIN = `${API_HOST}/user/signin`;
export const API_GOOGLE_LOGIN = `${API_HOST}/user/oauth2callback`;
export const API_CREATE_ACTIVITY = `${API_HOST}/Activity`;
export const API_RESET_PASSWORD = `${API_HOST}/user/resetPassword`;
export const API_FORGET_PASSWORD = `${API_HOST}/user/forgetPassword`;